[package]
name = "bread-dog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bd"
path = "src/main.rs"

[dependencies]
clap = "4.0"
anyhow = "1.0"
tokio = { version = "1.21", features = ["macros", "rt", "rt-multi-thread"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
dialoguer = "0.10"
dirs-next = "2.0"
